[package]
name = "sv"
version = "0.3.0"
description = "A Rust library for working with the BSV blockchain."
repository = "https://github.com/murphsicles/rust-sv"
authors = ["Dr. Roy Murphy"]
keywords = ["bitcoin", "sv", "cash", "crypto"]
license = "MIT"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
digest = "0.10.7"
dns-lookup = "2.0.4"
hex = "0.4.3"
linked-hash-map = "0.5.6"
log = { version = "0.4.27", features = ["max_level_trace", "release_max_level_warn"] }
murmur3 = "0.5.2"
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.9.1"
ring = "0.17.14"
ripemd160 = "0.10.0"
bs58 = "0.5.1"
secp256k1 = "0.31.0"
snowflake = "1.3.0"

[dev-dependencies]
pretty_assertions = "1.4"

[profile.release]
opt-level = "s"
lto = true
