name: Publish to crates.io

on:
  push:
    tags:
      - 'v.0.4.0*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
